"""Synthetic card-transaction generator.

The public Kaggle credit-card dataset is 28 anonymised PCA components, which
makes feature engineering impossible to demonstrate and impossible to explain
to a non-technical stakeholder. This generator emits the raw fields a real
issuer actually sees (amount, merchant, channel, geography, timestamp) so the
rest of the pipeline can do the thing the job actually asks for: turn a raw
transaction log into causal features.

Fraud is not generated by flipping an independent coin per row. Real card
fraud arrives in *attacks*: a compromised card is tested with a small
authorisation, then drained over minutes to hours. Generating it that way is
what makes the velocity features in `features.py` meaningful, and it is why
the evaluation split in `train.py` has to be temporal.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
import pandas as pd

MERCHANT_CATEGORIES = [
    "grocery",
    "restaurant",
    "fuel",
    "retail",
    "travel",
    "electronics",
    "digital_goods",
    "gift_card",
]

# Share of legitimate spend by category, and the very different mix an
# attacker produces: resellable, instantly redeemable goods.
_LEGIT_CATEGORY_P = np.array([0.26, 0.21, 0.14, 0.18, 0.06, 0.08, 0.05, 0.02])
_FRAUD_CATEGORY_P = np.array([0.04, 0.05, 0.05, 0.12, 0.09, 0.26, 0.21, 0.18])

# Hour-of-day intensity. Legitimate spend tracks waking hours; attacks skew
# toward the small hours, but only mildly -- assuming otherwise is how a model
# ends up blind to daytime fraud.
_LEGIT_HOUR_W = np.array(
    [0.4, 0.3, 0.2, 0.2, 0.3, 0.6, 1.2, 2.0, 2.6, 2.8, 3.0, 3.4,
     3.6, 3.2, 3.0, 3.1, 3.4, 3.8, 3.6, 3.0, 2.4, 1.8, 1.2, 0.7]
)
_FRAUD_HOUR_W = np.array(
    [1.6, 1.8, 1.9, 1.7, 1.4, 1.0, 0.8, 0.8, 0.9, 1.0, 1.1, 1.2,
     1.2, 1.2, 1.1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.7, 1.6]
)


@dataclass
class GeneratorConfig:
    """Knobs for the synthetic issuer.

    `separability` interpolates every fraud-conditional parameter back toward
    its legitimate counterpart. At 1.0 attacks look maximally different from
    normal spend; at 0.0 they are indistinguishable and no model can beat
    chance. The default is tuned so a tuned GBDT lands near 0.8 PR-AUC --
    comparable to a production card model, and low enough that the threshold
    and cost analysis in `evaluate.py` is still the interesting part.
    """

    n_accounts: int = 12_000
    n_legit: int = 240_000
    fraud_rate: float = 0.0017  # ~1 in 600 transactions, in line with issuer reports
    start: str = "2024-01-01"
    days: int = 180
    separability: float = 0.62
    seed: int = 7
    categories: list[str] = field(default_factory=lambda: list(MERCHANT_CATEGORIES))

    def __post_init__(self) -> None:
        if not 0.0 <= self.separability <= 1.0:
            raise ValueError("separability must be in [0, 1]")
        if not 0.0 < self.fraud_rate < 0.5:
            raise ValueError("fraud_rate must be a small positive proportion")
        if self.n_legit < 1 or self.n_accounts < 1:
            raise ValueError("n_legit and n_accounts must be positive")


def _blend(legit, fraud, sep: float):
    """Pull a fraud-conditional parameter toward its legitimate counterpart."""
    return np.asarray(legit, dtype=float) + sep * (
        np.asarray(fraud, dtype=float) - np.asarray(legit, dtype=float)
    )


def _sample_hours(rng: np.random.Generator, weights: np.ndarray, size: int) -> np.ndarray:
    p = weights / weights.sum()
    return rng.choice(24, size=size, p=p)


def _make_timestamps(
    rng: np.random.Generator, start: pd.Timestamp, days: int, hours: np.ndarray
) -> pd.DatetimeIndex:
    day_offset = rng.integers(0, days, size=hours.size)
    minutes = rng.integers(0, 60, size=hours.size)
    seconds = rng.integers(0, 60, size=hours.size)
    deltas = (
        day_offset.astype("int64") * 86_400
        + hours.astype("int64") * 3_600
        + minutes.astype("int64") * 60
        + seconds.astype("int64")
    )
    return start + pd.to_timedelta(deltas, unit="s")


def _account_profiles(rng: np.random.Generator, n_accounts: int) -> pd.DataFrame:
    """Each account gets a spend level it returns to and an age."""
    return pd.DataFrame(
        {
            "account_id": np.arange(n_accounts),
            "log_mu": rng.normal(3.25, 0.45, size=n_accounts),  # median spend ~$26
            "account_age_days": rng.integers(20, 3_000, size=n_accounts),
        }
    )


def _generate_legit(
    rng: np.random.Generator, cfg: GeneratorConfig, profiles: pd.DataFrame
) -> pd.DataFrame:
    n = cfg.n_legit
    # Transaction counts per account follow a power law: a minority of
    # accounts generates most of the volume.
    weights = rng.pareto(1.6, size=cfg.n_accounts) + 1.0
    account_id = rng.choice(cfg.n_accounts, size=n, p=weights / weights.sum())
    prof = profiles.iloc[account_id].reset_index(drop=True)

    hours = _sample_hours(rng, _LEGIT_HOUR_W, n)
    amount = np.exp(rng.normal(prof["log_mu"].to_numpy(), 0.85))
    category = rng.choice(cfg.categories, size=n, p=_LEGIT_CATEGORY_P)

    # Most legitimate spend happens close to home; the tail is travel.
    travel = rng.random(n) < 0.06
    distance = np.where(
        travel,
        rng.gamma(3.0, 260.0, size=n),
        np.abs(rng.normal(0.0, 9.0, size=n)),
    )

    return pd.DataFrame(
        {
            "account_id": prof["account_id"].to_numpy(),
            "timestamp": _make_timestamps(rng, pd.Timestamp(cfg.start), cfg.days, hours),
            "amount": np.round(amount, 2),
            "merchant_category": category,
            "card_present": rng.random(n) < 0.55,
            "is_foreign": (rng.random(n) < 0.035) | (travel & (rng.random(n) < 0.35)),
            "distance_from_home_km": np.round(distance, 1),
            "account_age_days": prof["account_age_days"].to_numpy(),
            "is_fraud": 0,
        }
    )


def _generate_attacks(
    rng: np.random.Generator, cfg: GeneratorConfig, profiles: pd.DataFrame, n_fraud: int
) -> pd.DataFrame:
    """Bursts of up to six transactions on a single compromised card.

    The first transaction in a burst is often a deliberately tiny "card test"
    authorisation. That is exactly the case an amount threshold misses, and
    the reason the model is given account-history features rather than the
    raw amount alone.
    """
    sep = cfg.separability
    rows: list[dict] = []

    p_card_present = float(_blend(0.55, 0.06, sep))
    p_foreign = float(_blend(0.035, 0.42, sep))
    p_card_test = float(_blend(0.05, 0.45, sep))
    log_ratio_mu = float(_blend(0.0, 1.5, sep))
    distance_scale = float(_blend(40.0, 1_400.0, sep))
    cat_p = _blend(_LEGIT_CATEGORY_P, _FRAUD_CATEGORY_P, sep)
    cat_p = cat_p / cat_p.sum()
    hour_w = _blend(_LEGIT_HOUR_W, _FRAUD_HOUR_W, sep)

    emitted = 0
    while emitted < n_fraud:
        victim = int(rng.integers(0, cfg.n_accounts))
        prof = profiles.iloc[victim]
        burst_size = int(rng.integers(1, 7))
        start_hour = _sample_hours(rng, hour_w, 1)
        burst_start = _make_timestamps(
            rng, pd.Timestamp(cfg.start), cfg.days, start_hour
        )[0]
        burst_distance = distance_scale * float(rng.gamma(2.0, 0.5))
        foreign_burst = bool(rng.random() < p_foreign)

        offset_s = 0
        for j in range(burst_size):
            if emitted >= n_fraud:
                break
            # Tens of seconds to about an hour between attempts.
            offset_s += int(rng.exponential(900)) + 30
            if j == 0 and rng.random() < p_card_test:
                amount = float(rng.uniform(0.5, 4.0))
            else:
                # Drain attempts are large *relative to the victim's normal
                # spend*, which only a ratio feature can see.
                ratio = float(np.exp(rng.normal(log_ratio_mu, 0.9)))
                amount = float(np.exp(prof["log_mu"])) * ratio
            rows.append(
                {
                    "account_id": victim,
                    "timestamp": burst_start + pd.Timedelta(seconds=offset_s),
                    "amount": round(max(amount, 0.5), 2),
                    "merchant_category": str(rng.choice(cfg.categories, p=cat_p)),
                    "card_present": bool(rng.random() < p_card_present),
                    "is_foreign": foreign_burst,
                    "distance_from_home_km": round(burst_distance, 1),
                    "account_age_days": int(prof["account_age_days"]),
                    "is_fraud": 1,
                }
            )
            emitted += 1

    return pd.DataFrame(rows)


def generate_transactions(cfg: GeneratorConfig | None = None) -> pd.DataFrame:
    """Return a time-sorted transaction log with an `is_fraud` label."""
    cfg = cfg or GeneratorConfig()
    rng = np.random.default_rng(cfg.seed)
    profiles = _account_profiles(rng, cfg.n_accounts)

    legit = _generate_legit(rng, cfg, profiles)
    n_fraud = max(1, int(round(cfg.n_legit * cfg.fraud_rate / (1 - cfg.fraud_rate))))
    fraud = _generate_attacks(rng, cfg, profiles, n_fraud)

    df = pd.concat([legit, fraud], ignore_index=True)
    df = df.sort_values("timestamp", kind="mergesort").reset_index(drop=True)
    df["transaction_id"] = np.arange(len(df))
    df["card_present"] = df["card_present"].astype(bool)
    df["is_foreign"] = df["is_foreign"].astype(bool)
    df["is_fraud"] = df["is_fraud"].astype(np.int8)
    return df[
        [
            "transaction_id",
            "timestamp",
            "account_id",
            "amount",
            "merchant_category",
            "card_present",
            "is_foreign",
            "distance_from_home_km",
            "account_age_days",
            "is_fraud",
        ]
    ]


if __name__ == "__main__":  # pragma: no cover - manual inspection helper
    frame = generate_transactions()
    print(frame.head(10).to_string(index=False))
    print(f"\nrows={len(frame):,}  fraud_rate={frame['is_fraud'].mean():.4%}")
